"use strict";
var main;(function(){let DD=2463534242,Eo=()=>{let x=DD;x^=x<<13;x^=x>>>17;x^=x<<5;DD=x;return x;},D=f=>function(){return f(this);},H=f=>function(p1){return f(this,p1);},J=f=>function(p1,p2){return f(this,p1,p2);},Cb=f=>function(p1,p2,p3){return f(this,p1,p2,p3,p3);},DV=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=Bt(Y(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=W(args[i]);}FY(()=>{f.call(null,javaArgs);},callback);},Bg=target=>target.$clinit=()=>{},F7=obj=>{let cls=obj.constructor;let arrayDegree
=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},G=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0){superclass=Y();}return function(){superclass.call(this);};},Ci=cls=>FO(cls),Y=()=>E,F$=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},Ct=(name,
binaryName)=>{let cls=F$();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},Cj=Ct("char","C"),EV=Ct("int","I");
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}let EP=(a,b)=>a>b?1:a<b? -1:a===b?0:1,BF=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},BN=(a,b)=>(a>>>0)/(b>>>0)>>>0,F_=(a,b)=>(a>>>0)%(b>>>0)>>>0,B2=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;};
function Gz(lo,hi){this.lo=lo|0;this.hi=hi|0;}
if(typeof BigInt!=="function"){}else {}if(typeof BigInt!=='function'){function GD(lo,hi,sup){this.lo=lo;this.hi=hi;this.sup=sup;}
}else {}let Bt=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bu(cls))(data);},EQ=(cls,data)=>new (Bu(cls))(data);
if(typeof BigInt64Array!=='function'){}else {}let BD=sz=>new CS(new Uint16Array(sz)),D6=data=>{let buffer=new Uint16Array(data.length);buffer.set(data);return new CS(buffer);},Bu=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(Y()).call(this);this.data=data;}JavaArray.prototype=Object.create((Y()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str
+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.dF=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bu(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[Y()],primitive:false,superclass:Y(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject
=null;JavaArray.$array=null;result=JavaArray;cls.$array=JavaArray;}return result;},BX,EA=strings=>{E1();BX=new Array(strings.length);for(let i=0;i<strings.length;++i){BX[i]=CL(W(strings[i]));}},F=index=>BX[index],Dy=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},W=str=>str===null?null:CA(str),P=str=>str===null?null:str.cz,E1=()=>Bh(),CL;
{CL=str=>str;}let S=ex=>{throw E2(ex);},Bx=Symbol("javaException"),E2=ex=>{let err=ex.$jsException;if(!err){let javaCause=Gl(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new V("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bx]=ex;ex.$jsException=err;FD(err,ex);}return err;},FD=(err,ex)=>{if(typeof Ed==="function"&&err.stack){let stack=Ed(err.stack);let javaStack=
Bt(Eu(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=EE(W(element.className),W(element.methodName),W(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){EU(ex,javaStack);}}},V;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");V=function V(message,cause){let self=Reflect.construct(Error,[void 0,cause],V);Object.setPrototypeOf(self,V.prototype);self[defaultMessage]=message;return self;}
;V.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:V},message:{get(){try {let javaException=this[Bx];if(typeof javaException==='object'){let javaMessage=DQ(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {V=Error;}let D0=e=>e instanceof Error&&typeof e[Bx]==='object'?e[Bx]:null,DQ=t=>DF(t),Gl
=t=>DK(t),Eu=()=>GJ,EE=(className,methodName,fileName,lineNumber)=>{{return null;}},EU=(e,stack)=>{},Cv=null,E5=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}Cv=packages;},CB=data=>{let packages=Cv;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex
=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo
===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func
=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},FY=(runner,callback)=>{let result;try {result=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function E(){this.$id$=0;}
let I=a=>{return;},GI=()=>{let a=new E();I(a);return a;},F3=a=>{return BR(a);},Eg=(a,b)=>{return a!==b?0:1;},CZ=a=>{let b,c;b=FU(BR(a));c=U();L(L(c,F(0)),b);return Q(c);},BR=a=>{let b;b=a;if(!b.$id$)b.$id$=Eo();return a.$id$;};
function Bp(){let a=this;E.call(a);a.dw=null;a.dv=null;a.dq=0;a.dx=0;}
let Dx=a=>{a.dq=1;a.dx=1;a.f();},Gx=()=>{let a=new Bp();Dx(a);return a;},CV=(a,b)=>{a.dq=1;a.dx=1;a.f();a.dw=b;},GH=a=>{let b=new Bp();CV(b,a);return b;},ES=a=>{return a;},DF=a=>{return a.dw;},DK=a=>{return a.dv===a?null:a.dv;},Bo=G(Bp),B0=a=>{Dx(a);},Gt=()=>{let a=new Bo();B0(a);return a;},BT=(a,b)=>{CV(a,b);},GF=a=>{let b=new Bo();BT(b,a);return b;},K=G(Bo),Bf=a=>{B0(a);},Gv=()=>{let a=new K();Bf(a);return a;},Co=(a,b)=>{BT(a,b);},GE=a=>{let b=new K();Co(b,a);return b;},Bw=G(K),B3=a=>{Bf(a);},FZ=()=>{let a
=new Bw();B3(a);return a;},Gp=G(),F0=(b,c)=>{let d,e,f,g;d=b.data;e=BD(c);f=Dq(c,d.length);g=0;while(g<f){e.data[g]=d[g];g=g+1|0;}return e;};
function Cc(){let a=this;E.call(a);a.ds=null;a.dn=null;a.dB=null;a.dp=null;a.du=null;a.dh=null;a.dl=null;a.cI=null;a.cT=null;a.c0=null;a.cD=null;a.cB=null;a.de=0;}
let C5=null,BE=()=>{BE=Bg(Cc);D3();},Ds=(a,b)=>{BE();I(a);a.ds=M(F(1));a.dn=M(F(2));a.dB=M(F(3));a.dp=M(F(4));a.du=M(F(5));a.dh=M(F(6));a.dl=b;},F8=a=>{let b=new Cc();Ds(b,a);return b;},Ef=a=>{let b,c,d,e,f,g,h;b=32;a.cI=BB();a.cT=BB();a.c0=BB();a.cD=BB();c=0;while(c<21){d=0;while(d<19){a:{BE();e=C5.data[c].j(d);f=BF(d,b);g=BF(c,b);switch(e){case 32:a.cT.k(R(null,f+14|0,g+14|0,4,4));break a;case 80:break;case 87:h=16;a.c0.k(R(a.dh,f+8|0,g+8|0,h,h));break a;case 88:a.cI.k(R(a.ds,f,g,b,b));break a;case 98:a.cD.k(R(a.dn,
f,g,b,b));break a;case 111:a.cD.k(R(a.du,f,g,b,b));break a;case 112:a.cD.k(R(a.dp,f,g,b,b));break a;case 114:a.cD.k(R(a.dB,f,g,b,b));break a;default:break a;}a.cB=R(a.dl,f,g,b,b);}d=d+1|0;}c=c+1|0;}a.de=a.cT.m();},D3=()=>{C5=EQ(O,[F(7),F(8),F(9),F(10),F(11),F(12),F(13),F(14),F(15),F(16),F(17),F(14),F(17),F(18),F(9),F(19),F(20),F(21),F(22),F(23),F(7)]);};
function BH(){let a=this;E.call(a);a.cY=0;a.dD=0;a.cS=null;a.cV=null;a.dA=null;a.c5=null;}
let BO=(a,b)=>{I(a);a.c5=b;a.dD=b.cQ;a.cS=null;},Gu=a=>{let b=new BH();BO(b,a);return b;},Fa=a=>{if(a.cS!==null)return 1;while(a.cY<a.c5.cx.data.length){if(a.c5.cx.data[a.cY]!==null)return 1;a.cY=a.cY+1|0;}return 0;},DL=a=>{if(a.dD==a.c5.cQ)return;S(Ez());},CG=a=>{let b,c;DL(a);if(!a.o())S(DZ());if(a.cS===null){b=a.c5.cx.data;c=a.cY;a.cY=c+1|0;a.cV=b[c];a.cS=a.cV.cG;a.dA=null;}else{if(a.cV!==null)a.dA=a.cV;a.cV=a.cS;a.cS=a.cS.cG;}},C3=G(0),Z=G(0),Dk=G(),CD=a=>{I(a);},DP=()=>{let a=new Dk();CD(a);return a;},F9
=(a,b)=>{if(b<=0)S(CR());return a.p()*b|0;},EG=a=>{return Fc();},B_=G(),Bv=G(0),CM=G(B_),EC=null,BI=()=>{BI=Bg(CM);Em();},FU=b=>{BI();return Er(b,4);},Gd=b=>{let c,d,e;BI();if(!b)return 32;c=0;d=b>>>16|0;if(d)c=16;else d=b;e=d>>>8|0;if(!e)e=d;else c=c|8;d=e>>>4|0;if(!d)d=e;else c=c|4;e=d>>>2|0;if(!e)e=d;else c=c|2;if(e>>>1|0)c=c|1;return (32-c|0)-1|0;},Em=()=>{EC=Ci(EV);},C_=G(0),BJ=G(0),BK=G(),DO=a=>{I(a);},BY=G(),EB=null,ET=null,Bm=()=>{Bm=Bg(BY);Fw();},Ga=b=>{let c;Bm();c=b-65536|0;return (55296|c>>10&1023)
&65535;},FR=b=>{Bm();return (56320|b&1023)&65535;},Ca=(b,c)=>{Bm();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},Fw=()=>{EB=Ci(Cj);ET=Bt(BY,128);},Gh=G(),Er=(b,c)=>{let d,e,f,g,h,i,j,k;if(!b)return F(24);d=1<<c;e=d-1|0;f=(((32-Gd(b)|0)+c|0)-1|0)/c|0;g=BD(f);h=BF(f-1|0,c);i=0;while(h>=0){j=g.data;k=i+1|0;j[i]=Ca((b>>>h|0)&e,d);h=h-c|0;i=k;}return D8(g);},CP=G(0),Ec=G(),Fc=()=>{return FE();},FE=()=>{return Math.random();},Dq=(b,c)=>{if(b<c)c=b;return c;},CH=(b,c)=>{if(b
>c)c=b;return c;},Gm=G();
function De(){E.call(this);this.cy=null;}
let Dp=(a,b)=>{I(a);a.cy=b;},EX=a=>{let b=new De();Dp(b,a);return b;},FA=(a,b)=>{let c,d,e,f,g,h,i,j,k,l,m,n;c=(a.cy.w()).x();while(c.o()){d=c.y();if(d.cw!==null)b.drawImage(Bb(d.cw),d.cu,d.cv,d.cC,d.cL);}c="#ffffff";b.fillStyle=c;c=(a.cy.A()).x();while(c.o()){e=c.y();f=e.cu;g=e.cv;h=e.cC;i=e.cL;b.fillRect(f,g,h,i);}c=(a.cy.B()).x();while(c.o()){j=c.y();if(j.cw!==null)b.drawImage(Bb(j.cw),j.cu,j.cv,j.cC,j.cL);}k=a.cy.C();if(k!==null&&k.cw!==null)b.drawImage(Bb(k.cw),k.cu,k.cv,k.cC,k.cL);c=(a.cy.D()).x();while
(c.o()){l=c.y();m=l.cJ>0&&!((l.cJ/5|0)%2|0)?1:0;if(!m&&l.cw!==null)b.drawImage(Bb(l.cw),l.cu,l.cv,l.cC,l.cL);}n=a.cy.E();if(n.cw!==null)b.drawImage(Bb(n.cw),n.cu,n.cv,n.cC,n.cL);Gc(a,b);},Gc=(a,b)=>{let c,d,e,f;if(a.cy.G()>0){b.fillStyle="rgb(0,200,255)";c=a.cy.G()/300.0*576.0|0;b.fillRect(16.0,26.0,c,5.0);}b.font="bold 16px Arial";b.fillStyle="#ffffff";d=a.cy.H();e=U();Ba(L(e,F(25)),d);b.fillText(P(Q(e)),16.0,16.0);d=a.cy.J();e=U();Ba(L(e,F(26)),d);b.fillText(P(Q(e)),202.0,16.0);d=a.cy.K();e=U();Ba(L(e,F(27)),
d);b.fillText(P(Q(e)),376.0,16.0);d=a.cy.L();e=U();Ba(L(e,F(28)),d);b.fillText(P(Q(e)),544.0,16.0);if(a.cy.M()){b.fillStyle="rgba(0,0,0,0.706)";b.fillRect(0.0,266.0,608.0,145.0);b.fillStyle="#ff0000";b.font="bold 32px Arial";BA(a,b,F(29),316);b.fillStyle="#ffffff";b.font="18px Arial";d=a.cy.J();f=a.cy.K();e=U();Ba(L(Ba(L(e,F(26)),d),F(30)),f);BA(a,b,Q(e),351);b.fillStyle="#ffff00";b.font="16px Arial";BA(a,b,F(31),381);}if(a.cy.O()){b.fillStyle="rgba(0,0,0,0.627)";b.fillRect(0.0,296.0,608.0,80.0);b.fillStyle
="#00ffff";b.font="bold 30px Arial";BA(a,b,F(32),346);}},BA=(a,b,c,d)=>{let e,f,g;e=b.measureText(P(c)).width;f=(608.0-e)/2.0;g=d;b.fillText(P(c),f,g);},BG=G(0),FF=G(),Bk=(b,c)=>{let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},Bd=G(0),Cd=G(0),BM=G(),C8=a=>{I(a);},Fv=()=>{let a=new BM();C8(a);return a;},Fq=(a,b)=>{DX(b);},Ei=(a,b)=>{a.Q(CC(b));},BS=G(0),Dl=G(0),CW=G(Bw),C9=a=>{B3(a);},B$
=()=>{let a=new CW();C9(a);return a;},CQ=G(),N=null,DJ=null,Bj=null,Be=()=>{Be=Bg(CQ);Fm();},F1=b=>{let c,d,e,f,g;Be();c=window;d=c.document;e=d.getElementById("gameCanvas");f=608;e.width=f;f=672;e.height=f;Bj=e.getContext("2d");N=Es();DJ=EX(N);g=Fr();d.addEventListener("keyup",Bk(g,"handleEvent"));g=FW();d.addEventListener("keydown",Bk(g,"handleEvent"));g=Gr();setInterval(Bk(g,"onTimer"),50);},EY=()=>{let b,c;Be();N.U();Bj.clearRect(0.0,0.0,608.0,672.0);b=Bj;c="#000000";b.fillStyle=c;Bj.fillRect(0.0,0.0,608.0,
672.0);DJ.V(Bj);},FP=b=>{let c;Be();c=b;if(W(c.code).W(F(33)))b.preventDefault();},Gj=b=>{let c,d;Be();c=W(b.code);if(N.M()){if(!(!F(34).X(c)&&!F(35).X(c)))N.Y();return;}if(F(36).X(c)){N.Z();return;}if(N.O())return;a:{d=(-1);switch(c.ba()){case 251549619:if(!c.X(F(37)))break a;d=2;break a;case 930625636:if(!c.X(F(38)))break a;d=0;break a;case 977535019:if(!c.X(F(39)))break a;d=1;break a;case 977763216:if(!c.X(F(40)))break a;d=3;break a;default:}}b:{switch(d){case 0:break;case 1:N.bb(68);break b;case 2:N.bb(82);break b;case 3:N.bb(76);break b;default:break b;}N.bb(85);}},Fm
=()=>{return;},E9=G(),FB=(b,c,d)=>{if(b>=0&&c>=0&&c<=(d-b|0))return b;S(FZ());};
function Du(){let a=this;E.call(a);a.cu=0;a.cv=0;a.cC=0;a.cL=0;a.cw=null;a.df=null;a.dj=0;a.di=0;a.cR=0;a.cF=0;a.cE=0;a.cJ=0;}
let Cn=(a,b,c,d,e,f)=>{I(a);a.cR=85;a.cF=0;a.cE=0;a.cJ=0;a.cw=b;a.df=b;a.cu=c;a.cv=d;a.cC=e;a.cL=f;a.dj=c;a.di=d;},R=(a,b,c,d,e)=>{let f=new Du();Cn(f,a,b,c,d,e);return f;},Gk=(a,b,c)=>{let d,e,f;d=a.cR;a.cR=b;a.bc();a.cu=a.cu+a.cF|0;a.cv=a.cv+a.cE|0;e=c.x();while(e.o()){f=e.y();if(X(a,f)){a.cu=a.cu-a.cF|0;a.cv=a.cv-a.cE|0;a.cR=d;a.bc();return;}}},Gs=a=>{let b;a:{b=8;switch(a.cR){case 68:break;case 76:a.cF=(-8);a.cE=0;break a;case 82:a.cF=b;a.cE=0;break a;case 85:a.cF=0;a.cE=(-8);break a;default:break a;}a.cF
=0;a.cE=b;}},EW=a=>{a.cu=a.dj;a.cv=a.di;},X=(b,c)=>{return b.cu<((c.cu+c.cC|0)-5|0)&&((b.cu+b.cC|0)-5|0)>c.cu&&b.cv<((c.cv+c.cL|0)-5|0)&&((b.cv+b.cL|0)-5|0)>c.cv?1:0;},Ew=G(),Cm=G(0);
function Bz(){let a=this;E.call(a);a.c3=null;a.da=null;}
let Cg=(a,b,c)=>{I(a);a.c3=b;a.da=c;},GC=(a,b)=>{let c=new Bz();Cg(c,a,b);return c;};
function B1(){let a=this;Bz.call(a);a.c_=0;a.cG=null;}
let CO=(a,b,c)=>{Cg(a,b,null);a.c_=c;},Ek=(a,b)=>{let c=new B1();CO(c,a,b);return c;},Cr=G(0),CI=G(0);
function Bq(){let a=this;E.call(a);a.cA=null;a.cH=0;}
let BQ=a=>{B9(a,16);},GB=()=>{let a=new Bq();BQ(a);return a;},B9=(a,b)=>{I(a);a.cA=BD(b);},Gw=a=>{let b=new Bq();B9(b,a);return b;},CF=(a,b)=>{return a.bg(a.cH,b);},Cl=(a,b,c)=>{let d,e,f;if(b>=0&&b<=a.cH){if(c===null)c=F(41);else if(c.bh())return a;a.bi(a.cH+c.bj()|0);d=a.cH-1|0;while(d>=b){a.cA.data[d+c.bj()|0]=a.cA.data[d];d=d+(-1)|0;}a.cH=a.cH+c.bj()|0;d=0;while(d<c.bj()){e=a.cA.data;f=b+1|0;e[b]=c.j(d);d=d+1|0;b=f;}return a;}S(B$());},Cw=(a,b)=>{return a.bk(b,10);},FH=(a,b,c)=>{return a.bl(a.cH,b,c);},Ep
=(a,b,c,d)=>{let e,f,g,h,i,j,k,l;e=1;if(c<0){e=0;c= -c|0;}a:{if(B2(c,d)<0){if(e)Ce(a,b,b+1|0);else{Ce(a,b,b+2|0);f=a.cA.data;g=b+1|0;f[b]=45;b=g;}a.cA.data[b]=Ca(c,d);}else{h=1;i=1;j=BN((-1),d);b:{while(true){k=BF(h,d);if(B2(k,c)>0){k=h;break b;}i=i+1|0;if(B2(k,j)>0)break;h=k;}}if(!e)i=i+1|0;Ce(a,b,b+i|0);if(e)l=b;else{f=a.cA.data;l=b+1|0;f[b]=45;}while(true){if(!k)break a;f=a.cA.data;g=l+1|0;f[l]=Ca(BN(c,k),d);c=F_(c,k);k=BN(k,d);l=g;}}}return a;},CN=(a,b,c)=>{return a.bn(b,c===null?F(41):c.e());},Cp=(a,b)=>
{let c;if(a.cA.data.length>=b)return;c=a.cA.data.length>=1073741823?2147483647:CH(b,CH(a.cA.data.length*2|0,5));a.cA=F0(a.cA,c);},C6=a=>{return E6(a.cA,0,a.cH);},Ce=(a,b,c)=>{let d,e;d=a.cH-b|0;a.bi((a.cH+c|0)-b|0);e=d-1|0;while(e>=0){a.cA.data[c+e|0]=a.cA.data[b+e|0];e=e+(-1)|0;}a.cH=a.cH+(c-b|0)|0;},DN=G(0),CE=G(Bq),CY=a=>{BQ(a);},U=()=>{let a=new CE();CY(a);return a;},L=(a,b)=>{CF(a,b);return a;},Ba=(a,b)=>{Cw(a,b);return a;},Fg=(a,b,c)=>{CN(a,b,c);return a;},Fy=(a,b,c)=>{Cl(a,b,c);return a;},Q=a=>{return C6(a);},FK
=(a,b)=>{Cp(a,b);},EI=(a,b,c)=>{return a.bt(b,c);},F6=(a,b,c)=>{return a.bu(b,c);},B6=G(),Dh=a=>{I(a);},Gr=()=>{let a=new B6();Dh(a);return a;},EJ=a=>{EY();},ER=a=>{a.bw();},Do=G(K),Dr=a=>{Bf(a);},Ez=()=>{let a=new Do();Dr(a);return a;},BZ=G(0),B5=G(),C7=a=>{I(a);},FW=()=>{let a=new B5();C7(a);return a;},FL=(a,b)=>{FP(b);},Fb=(a,b)=>{a.by(b);},C$=G(0),B4=G(),C0=a=>{I(a);},Fr=()=>{let a=new B4();C0(a);return a;},FT=(a,b)=>{Gj(b);},El=(a,b)=>{a.by(b);};
function Dv(){let a=this;E.call(a);a.ct=null;a.cW=null;a.c1=null;a.dd=null;a.dr=null;a.dC=null;a.dt=null;a.c9=null;a.dz=null;a.cM=0;a.c2=0;a.cU=0;a.c7=0;a.c6=0;a.cX=0;a.cK=0;a.c8=0;a.cP=0;a.c4=0;a.cO=null;a.db=0;}
let DG=a=>{I(a);a.cW=DP();a.c1=D6([85,68,76,82]);a.cM=0;a.c2=0;a.cU=3;a.c7=1;a.c6=0;a.cX=0;a.cK=0;a.c8=0;a.cP=0;a.c4=0;a.cO=null;a.db=0;a.c9=M(F(42));a.dr=M(F(43));a.dC=M(F(44));a.dt=M(F(45));a.dd=M(F(46));a.dz=M(F(47));a.ct=F8(a.c9);BU(a);},Es=()=>{let a=new Dv();DG(a);return a;},BU=a=>{a.ct.bC();a.cO=null;a.cP=0;a.db=0;a.c4=0;a.cK=0;Ff(a);},Ff=a=>{let b,c;b=a.ct.cD.x();while(b.o()){c=b.y();c.bE(a.c1.data[a.cW.bF(4)],a.ct.cI);}},FI=a=>{return a.ct.cI;},DW=a=>{return a.ct.cT;},FQ=a=>{return a.ct.c0;},D1=a=>
{return a.ct.cD;},FV=a=>{return a.ct.cB;},Fx=a=>{return a.cO;},D$=a=>{return a.cM;},FG=a=>{return a.c2;},D5=a=>{return a.cU;},Ge=a=>{return a.c7;},DU=a=>{return a.c6;},DR=a=>{return a.cX;},Gi=a=>{return a.cK;},D4=(a,b)=>{a:{a.ct.cB.bE(b,a.ct.cI);switch(a.ct.cB.cR){case 68:break;case 76:a.ct.cB.cw=a.dt;break a;case 82:a.ct.cB.cw=a.c9;break a;case 85:a.ct.cB.cw=a.dr;break a;default:break a;}a.ct.cB.cw=a.dC;}},E0=a=>{a.cX=a.cX?0:1;},FX=a=>{a.cM=0;a.cU=3;a.c7=1;a.c6=0;a.cX=0;BU(a);},EK=a=>{if(!a.cX&&!a.c6){Fs(a);E$(a);Ea(a);Ej(a);Eb(a);EF(a);Fl(a);Fi(a);return;}},Fs
=a=>{let b,c,d;b=a.ct.cB;b.cu=b.cu+b.cF|0;b.cv=b.cv+b.cE|0;if((b.cu+b.cC|0)<=0)b.cu=608;else if(b.cu>=608)b.cu= -b.cC|0;c=a.ct.cI.x();while(c.o()){d=c.y();if(X(d,b)){b.cu=b.cu-b.cF|0;b.cv=b.cv-b.cE|0;}}},E$=a=>{let b,c,d,e,f;b=608;c=a.ct.cD.x();while(c.o()){d=c.y();if(d.cv==288&&d.cu==128)d.bE(a.c1.data[a.cW.bF(4)],a.ct.cI);d.cv=d.cv+d.cE|0;d.cu=d.cu+d.cF|0;if((d.cu+d.cC|0)<=0)d.cu=b;else if(d.cu>=b)d.cu= -d.cC|0;e=a.ct.cI.x();while(e.o()){f=e.y();if(X(d,f)){d.cv=d.cv-d.cE|0;d.cu=d.cu-d.cF|0;d.bE(a.c1.data[a.cW.bF(4)],
a.ct.cI);}}if(d.cJ>0){d.cJ=d.cJ-1|0;if(!d.cJ&&a.cK>0)d.cw=a.dd;}}},Ea=a=>{let b,c;b=a.ct.cD.x();while(b.o()){c=b.y();if(!X(c,a.ct.cB))continue;if(c.cJ>0)continue;if(a.cK<=0){a.cU=a.cU-1|0;if(a.cU){Fu(a);return;}a.c6=1;if(a.cM>a.c2)a.c2=a.cM;return;}Bs(a,200*(1<<a.c8)|0);a.c8=a.c8+1|0;c.bQ();c.cw=c.df;c.cJ=80;c.bE(a.c1.data[a.cW.bF(4)],a.ct.cI);}},Ej=a=>{let b,c,d;b=null;c=a.ct.cT.x();a:{while(true){if(!c.o()){d=b;break a;}d=c.y();if(X(a.ct.cB,d))break;}}if(d!==null){a.ct.cT.bR(d);Bs(a,10);a.c4=a.c4+1|0;}},Eb
=a=>{let b,c,d;b=null;c=a.ct.c0.x();a:{while(true){if(!c.o()){d=b;break a;}d=c.y();if(X(a.ct.cB,d))break;}}if(d!==null){a.ct.c0.bR(d);Bs(a,50);Ee(a);}},EF=a=>{let b;if(a.cO!==null&&X(a.ct.cB,a.cO)){Bs(a,100);a.cO=null;a.cP=0;}b=a.ct.de>0&&a.c4>=(a.ct.de/2|0)?1:0;if(!a.db&&a.cO===null&&!a.cP&&b){Fo(a);a.db=1;}},Fl=a=>{let b;if(a.cP>0){b=a.cP-1|0;a.cP=b;if(!b)a.cO=null;}if(a.cK>0){b=a.cK-1|0;a.cK=b;if(!b)Di(a);}},Fi=a=>{if(a.ct.cT.bh()&&a.ct.c0.bh()){a.c7=a.c7+1|0;BU(a);}},Bs=(a,b)=>{a.cM=a.cM+b|0;if(a.cM>a.c2)a.c2
=a.cM;},Ee=a=>{let b,c;a.cK=300;a.c8=0;b=a.ct.cD.x();while(b.o()){c=b.y();c.cw=a.dd;}},Di=a=>{let b,c;b=a.ct.cD.x();while(b.o()){c=b.y();c.cw=c.df;}},Fu=a=>{let b,c,d;b=a.ct.cB;b.bQ();b.cF=0;b.cE=0;b.cR=82;b.cw=a.c9;a.cK=0;Di(a);c=a.ct.cD.x();while(c.o()){d=c.y();d.bQ();d.cJ=0;d.bE(a.c1.data[a.cW.bF(4)],a.ct.cI);}},Fo=a=>{let b;b=32;a.cO=R(a.dz,288,96,b,b);a.cP=200;},Bl=G(BK),B7=a=>{DO(a);};
function Dt(){Bl.call(this);this.dm=null;}
let DI=(a,b)=>{a.dm=b;B7(a);},En=a=>{let b=new Dt();DI(b,a);return b;},DS=a=>{return D9(a.dm);},DA=G(0),CK=G(BH),Cy=(a,b)=>{BO(a,b);},D9=a=>{let b=new CK();Cy(b,a);return b;},Fh=a=>{CG(a);return a.cV.c3;};
function B8(){E.call(this);this.dg=null;}
let Ck=a=>{I(a);};
function By(){let a=this;B8.call(a);a.cN=0;a.cx=null;a.cQ=0;a.dy=0.0;a.dc=0;}
let F2=(a,b)=>{return Bt(B1,b);},Cq=a=>{BP(a,16);},Gf=()=>{let a=new By();Cq(a);return a;},BP=(a,b)=>{BW(a,b,0.75);},Gy=a=>{let b=new By();BP(b,a);return b;},Cx=b=>{let c,d;if(b>=1073741824)return 1073741824;if(!b)return 16;c=b-1|0;d=c|c>>1;d=d|d>>2;d=d|d>>4;d=d|d>>8;d=d|d>>16;return d+1|0;},BW=(a,b,c)=>{let d;Ck(a);if(b>=0&&c>0.0){d=Cx(b);a.cN=0;a.cx=a.bZ(d);a.dy=c;Dd(a);return;}S(CR());},GG=(a,b)=>{let c=new By();BW(c,a,b);return c;},Dd=a=>{a.dc=a.cx.data.length*a.dy|0;},Dc=(a,b,c,d)=>{let e;e=a.cx.data[c];while
(e!==null&&!(e.c_==d&&DE(b,e.c3))){e=e.cG;}return e;},DC=a=>{let b;b=a.cx.data[0];while(b!==null&&b.c3!==null){b=b.cG;}return b;},Fe=a=>{return a.cN?0:1;},FN=a=>{if(a.dg===null)a.dg=En(a);return a.dg;},E_=(a,b,c)=>{return FJ(a,b,c);},FJ=(a,b,c)=>{let d,e,f,g,h;if(b===null){d=DC(a);if(d===null){a.cQ=a.cQ+1|0;d=C4(a,null,0,0);e=a.cN+1|0;a.cN=e;if(e>a.dc)a.b5();}}else{f=b.ba();g=f&(a.cx.data.length-1|0);d=Dc(a,b,g,f);if(d===null){a.cQ=a.cQ+1|0;d=C4(a,b,g,f);e=a.cN+1|0;a.cN=e;if(e>a.dc)a.b5();}}h=d.da;d.da=c;return h;},C4
=(a,b,c,d)=>{let e;e=Ek(b,d);e.cG=a.cx.data[c];a.cx.data[c]=e;return e;},Fz=(a,b)=>{let c,d,e,f,g,h,i;c=Cx(!b?1:b<<1);d=a.bZ(c);e=0;while(e<a.cx.data.length){f=a.cx.data[e];a.cx.data[e]=null;while(f!==null){g=d.data;h=f.c_&(c-1|0);i=f.cG;f.cG=g[h];g[h]=f;f=i;}e=e+1|0;}a.cx=d;Dd(a);},Ft=a=>{a.b8(a.cx.data.length);},ED=(a,b)=>{let c;c=Cz(a,b);if(c===null)return null;return c.da;},Cz=(a,b)=>{let c,d,e,f,g;a:{c=0;d=null;if(b===null){e=a.cx.data[0];while(e!==null){if(e.c3===null)break a;f=e.cG;d=e;e=f;}}else{g=b.ba();c
=g&(a.cx.data.length-1|0);e=a.cx.data[c];while(e!==null&&!(e.c_==g&&DE(b,e.c3))){f=e.cG;d=e;e=f;}}}if(e===null)return null;if(d!==null)d.cG=e.cG;else a.cx.data[c]=e.cG;a.cQ=a.cQ+1|0;a.cN=a.cN-1|0;return e;},Fp=a=>{return a.cN;},DE=(b,c)=>{return b!==c&&!b.X(c)?0:1;},EZ=G(K);
function Ch(){E.call(this);this.dk=null;}
let Ex=null,BC=null,Bi=null,Br=null,DM=null,Cs=null,C1=null,T=()=>{T=Bg(Ch);Fd();},Ey=(a,b)=>{T();I(a);a.dk=b;},Bn=a=>{let b=new Ch();Ey(b,a);return b;},Dm=b=>{let c,d,e,f,g,h,i,j,k;T();if(b===null)return null;c=b;d=W(typeof c);e=!d.X(F(48))&&!d.X(F(49))?0:1;if(e&&b[Bc]===true)return b;if(BC!==null){if(e){f=BC.get(c);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Bn(c);BC.set(c,new WeakRef(h));return h;}if(d.X(F(50))){i=c;f=Bi.get(i);g=(typeof f=='undefined'?1:0)?void 0
:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Bn(c);j=h;Bi.set(i,new WeakRef(j));Dz(Cs,j,i);return h;}if(d.X(F(51))){k=c;f=Br.get(k);g=(typeof f=='undefined'?1:0)?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Bn(c);j=h;Br.set(k,new WeakRef(j));Dz(C1,j,k);return h;}if(d.X(F(52))){f=DM;g=f===null?void 0:f.deref();if(!(typeof g=='undefined'?1:0))return g;h=Bn(c);j=h;DM=new WeakRef(j);return h;}}return Bn(c);},Bb=b=>{T();if(b===null)return null;return b[Bc]===true?b:b.dk;},CC=b=>{T();if(b===
null)return null;return b instanceof Y()?b:Dm(b);},D2=b=>{let c,d;T();c=Br;d=Bb(b);c.delete(d);},DX=b=>{let c,d;T();c=Bi;d=Bb(b);c.delete(d);},Fd=()=>{let b,c;Ex=new WeakMap();b=!(typeof WeakRef!=='undefined'?1:0)?null:new WeakMap();BC=b;b=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();Bi=b;b=!(typeof WeakRef!=='undefined'?1:0)?null:new Map();Br=b;if(Bi===null)b=null;else{c=Fv();b=new FinalizationRegistry(Bk(c,"accept"));}Cs=b;if(Br===null)b=null;else{c=D_();b=new FinalizationRegistry(Bk(c,"accept"));}C1
=b;},Dz=(b,c,d)=>{return b.register(c,d);};
function BV(){Bl.call(this);this.cZ=null;}
let Dg=a=>{Cf(a,Gf());},BB=()=>{let a=new BV();Dg(a);return a;},Cf=(a,b)=>{B7(a);a.cZ=b;},GA=a=>{let b=new BV();Cf(b,a);return b;},E3=(a,b)=>{return a.cZ.cb(b,a)!==null?0:1;},FM=a=>{return a.cZ.bh();},FC=a=>{return (a.cZ.cc()).x();},DT=(a,b)=>{return a.cZ.cd(b)===null?0:1;},Go=a=>{return a.cZ.m();},Fj=G(),M=b=>{let c,d,e,f,g,h;c=b.ce(47);d=c<0?b:b.cf(c+1|0);e=d.ce(46);if(e>=0)d=d.cg(0,e);f=window.document;g=U();L(L(g,F(53)),d);d=f.getElementById(P(Q(g)));if(d===null){d=f.createElement("img");g=b.cf(b.ce(47)
+1|0);h=U();L(L(h,F(54)),g);d.src=P(Q(h));}return Dm(d);},EL=G();
function O(){E.call(this);this.c$=0;}
let DY=null,CT=null,Eq=null,Bh=()=>{Bh=Bg(O);FS();},CX=a=>{Bh();I(a);a.cz="";},Gb=()=>{let a=new O();CX(a);return a;},Df=(a,b)=>{let c;Bh();c=b.data;I(a);a.cz=Dy(b.data,0,c.length);},D8=a=>{let b=new O();Df(b,a);return b;},Dw=(a,b)=>{a.cz=b;},CA=a=>{let b=new O();Dw(b,a);return b;},DH=(a,b,c,d)=>{let e;Bh();e=b.data;I(a);FB(c,d,e.length);a.cz=Dy(b.data,c,d);},E6=(a,b,c)=>{let d=new O();DH(d,a,b,c);return d;},Gg=(a,b)=>{if(b>=0&&b<a.cz.length)return a.cz.charCodeAt(b);S(B$());},Fk=a=>{return a.cz.length;},E4
=a=>{return a.cz.length?0:1;},Ev=(a,b,c)=>{let d,e,f;if((c+b.bj()|0)>a.bj())return 0;d=0;while(d<b.bj()){e=b.j(d);f=c+1|0;if(e!=a.j(c))return 0;d=d+1|0;c=f;}return 1;},E8=(a,b)=>{if(a===b)return 1;return a.ci(b,0);},Gn=(a,b,c)=>{let d,e,f,g,h;d=Dq(c,a.bj()-1|0);if(b<65536){e=b&65535;while(true){if(d<0)return (-1);if(a.cz.charCodeAt(d)==e)break;d=d+(-1)|0;}return d;}f=Ga(b);g=FR(b);while(true){if(d<1)return (-1);if(a.cz.charCodeAt(d)==g){h=d-1|0;if(a.cz.charCodeAt(h)==f)break;}d=d+(-1)|0;}return h;},Eh=(a,b)=>
{return a.cl(b,a.bj()-1|0);},EO=(a,b,c)=>{let d,e;d=a.cz.length;e=EP(b,c);if(!e)return CT;if(!b&&c==d)return a;if(b>=0&&e<=0&&c<=d)return CA(a.cz.substring(b,c));S(B$());},Et=(a,b)=>{return a.cg(b,a.bj());},EM=a=>{return a;},Gq=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof O))return 0;c=b;return a.cz!==c.cz?0:1;},F5=a=>{let b;a:{if(!a.c$){b=0;while(true){if(b>=a.cz.length)break a;a.c$=(31*a.c$|0)+a.cz.charCodeAt(b)|0;b=b+1|0;}}}return a.c$;},FS=()=>{DY=BD(0);CT=Gb();Eq=D7();},BL=G(),Dj=a=>{I(a);},D_=()=>
{let a=new BL();Dj(a);return a;},EH=(a,b)=>{D2(b);},F4=(a,b)=>{a.Q(CC(b));},DB=G(K),C2=a=>{Bf(a);},DZ=()=>{let a=new DB();C2(a);return a;},Fn=G(),Da=G(K),CJ=a=>{Bf(a);},CR=()=>{let a=new Da();CJ(a);return a;};
function Dn(){E.call(this);this.dE=null;}
let EN=(a,b)=>{let c;I(a);a.dE=b;c=a;b.classObject=c;},E7=a=>{let b=new Dn();EN(b,a);return b;},FO=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null)c=E7(b);return c;},CU=G(0),Db=G(),Cu=a=>{I(a);},D7=()=>{let a=new Db();Cu(a);return a;};
E5([]);
CB([E,0,0,[],0,3,0,0,["ba",D(F3),"X",H(Eg),"e",D(CZ),"a",D(BR)],Bp,0,E,[],0,3,0,0,["f",D(ES),"co",D(DF),"cp",D(DK)],Bo,0,Bp,[],0,3,0,0,["c",D(B0),"g",H(BT)],K,0,Bo,[],0,3,0,0,["c",D(Bf),"g",H(Co)],Bw,0,K,[],0,3,0,0,["c",D(B3)],Gp,0,E,[],0,3,0,0,0,Cc,0,E,[],0,3,0,BE,["bA",H(Ds),"bC",D(Ef)],BH,0,E,[],0,0,0,0,["bV",H(BO),"o",D(Fa),"n",D(DL),"bW",D(CG)],C3,0,E,[],3,3,0,0,0,Z,0,E,[],3,3,0,0,0,Dk,0,E,[C3,Z],0,3,0,0,["c",D(CD),"bF",H(F9),"p",D(EG)],B_,0,E,[Z],1,3,0,0,0,Bv,0,E,[],3,3,0,0,0,CM,0,B_,[Bv],0,3,0,BI,0,C_,
0,E,[],3,3,0,0,0,BJ,0,E,[C_],3,3,0,0,0,BK,0,E,[BJ],1,3,0,0,["c",D(DO)],BY,0,E,[Bv],0,3,0,Bm,0,Gh,0,E,[],4,3,0,0,0,CP,0,E,[],3,3,0,0,0,Ec,0,E,[],4,3,0,0,0,Gm,0,E,[],4,3,0,0,0,De,0,E,[],0,3,0,0,["S",H(Dp),"V",H(FA)],BG,0,E,[],3,3,0,0,0,FF,0,E,[],4,0,0,0,0,Bd,0,E,[],3,3,0,0,0,Cd,0,E,[Bd],3,3,0,0,0,BM,0,E,[Cd],0,3,0,0,["c",D(C8),"Q",H(Fq),"cq",H(Ei)],BS,0,E,[],3,3,0,0,0,Dl,0,E,[BJ],3,3,0,0,0,CW,0,Bw,[],0,3,0,0,["c",D(C9)],CQ,0,E,[],0,3,0,Be,0,E9,0,E,[],4,3,0,0,0,Du,0,E,[],0,3,0,0,["l",function(b,c,d,e,f){Cn(this,
b,c,d,e,f);},"bE",J(Gk),"bc",D(Gs),"bQ",D(EW)],Ew,0,E,[Bd],0,3,0,0,0,Cm,0,E,[],3,3,0,0,0,Bz,0,E,[Cm,BG],0,0,0,0,["be",J(Cg)],B1,0,Bz,[],0,0,0,0,["b7",J(CO)],Cr,0,E,[],3,3,0,0,0,CI,0,E,[Bd],3,3,0,0,0,Bq,0,E,[Z,BS],0,0,0,0,["c",D(BQ),"bf",H(B9),"br",H(CF),"bn",J(Cl),"bs",H(Cw),"bk",J(FH),"bl",Cb(Ep),"bg",J(CN),"bi",H(Cp),"e",D(C6)],DN,0,E,[],3,3,0,0,0,CE,0,Bq,[DN],0,3,0,0,["c",D(CY),"d",H(L),"I",H(Ba),"bt",J(Fg),"bu",J(Fy),"e",D(Q),"bi",H(FK),"bg",J(EI),"bn",J(F6)],B6,0,E,[CI],0,3,0,0,["c",D(Dh),"bw",D(EJ),"cr",
D(ER)],Do,0,K,[],0,3,0,0,["c",D(Dr)],BZ,0,E,[Bd],3,3,0,0,0,B5,0,E,[BZ],0,3,0,0,["c",D(C7),"by",H(FL),"cs",H(Fb)],C$,0,E,[],3,3,0,0,0,B4,0,E,[BZ],0,3,0,0,["c",D(C0),"by",H(FT),"cs",H(El)],Dv,0,E,[],0,3,0,0,["c",D(DG),"w",D(FI),"A",D(DW),"B",D(FQ),"D",D(D1),"E",D(FV),"C",D(Fx),"J",D(D$),"K",D(FG),"H",D(D5),"L",D(Ge),"M",D(DU),"O",D(DR),"G",D(Gi),"bb",H(D4),"Z",D(E0),"Y",D(FX),"U",D(EK)]]);
CB([Bl,0,BK,[Dl],1,3,0,0,["c",D(B7)],Dt,0,Bl,[],0,0,0,0,["bV",H(DI),"x",D(DS)],DA,0,E,[],3,3,0,0,0,CK,0,BH,[DA],0,0,0,0,["bV",H(Cy),"y",D(Fh)],B8,0,E,[CP],1,3,0,0,["c",D(Ck)],By,0,B8,[BG,Z],0,3,0,0,["bZ",H(F2),"c",D(Cq),"bf",H(BP),"bX",J(BW),"b6",Cb(Dc),"b3",D(DC),"bh",D(Fe),"cc",D(FN),"cb",J(E_),"b8",H(Fz),"b5",D(Ft),"cd",H(ED),"b9",H(Cz),"m",D(Fp)],EZ,0,K,[],0,3,0,0,0,Ch,0,E,[],4,3,0,T,0,BV,0,Bl,[BG,Z],0,3,0,0,["c",D(Dg),"bV",H(Cf),"k",H(E3),"bh",D(FM),"x",D(FC),"bR",H(DT),"m",D(Go)],Fj,0,E,[],4,3,0,0,0,EL,
0,E,[],4,3,0,0,0,O,0,E,[Z,Bv,BS],0,3,0,Bh,["c",D(CX),"u",H(Df),"bA",H(Dw),"bq",Cb(DH),"j",H(Gg),"bj",D(Fk),"bh",D(E4),"ci",J(Ev),"W",H(E8),"cl",J(Gn),"ce",H(Eh),"cg",J(EO),"cf",H(Et),"e",D(EM),"X",H(Gq),"ba",D(F5)],BL,0,E,[Cd],0,3,0,0,["c",D(Dj),"Q",H(EH),"cq",H(F4)],DB,0,K,[],0,3,0,0,["c",D(C2)],Fn,0,E,[Bd],1,3,0,0,0,Da,0,K,[],0,3,0,0,["c",D(CJ)],Dn,0,E,[C$,Cr],0,3,0,0,0,CU,0,E,[],3,3,0,0,0,Db,0,E,[CU],0,3,0,0,["c",D(Cu)]]);
let CS=Bu(Cj);
EA(["<java_object>@","/images/wall.png","/images/blueGhost.png","/images/redGhost.png","/images/pinkGhost.png","/images/orangeGhost.png","/images/powerFood.png","XXXXXXXXXXXXXXXXXXX","XW       X       WX","X XX XXX X XXX XX X","X                 X","X XX X XXXXX X XX X","X    X       X    X","XXXX XXXX XXXX XXXX","OOOX X       X XOOO","XXXX X XXrXX X XXXX","O       bpo       O","XXXX X XXXXX X XXXX","X        X        X","X  X     P     X  X","XX X X XXXXX X X XX","X    X   X   X    X","X XXXXXX X XXXXXX X",
"XW               WX","0","Lives: ","Score: ","Best: ","Lvl: ","GAME OVER","   Best: ","Press ENTER or SPACE to restart","PAUSED  -  P to resume","Arrow","Enter","Space","KeyP","ArrowRight","ArrowUp","ArrowDown","ArrowLeft","null","/images/pacmanRight.png","/images/pacmanUp.png","/images/pacmanDown.png","/images/pacmanLeft.png","/images/scaredGhost.png","/images/cherry.png","object","function","string","number","undefined","img-","images/"]);
O.prototype.toString=function(){return P(this);};
O.prototype.valueOf=O.prototype.toString;E.prototype.toString=function(){return P(CZ(this));};
E.prototype.__teavm_class__=function(){return F7(this);};
let C=DV(F1);
C.javaException=D0;
let Bc=Symbol('jsoClass');
(()=>{let c;c=BM.prototype;c[Bc]=true;c.accept=c.cq;c=B6.prototype;c[Bc]=true;c.onTimer=c.cr;c=B5.prototype;c[Bc]=true;c.handleEvent=c.cs;c=B4.prototype;c[Bc]=true;c.handleEvent=c.cs;c=BL.prototype;c[Bc]=true;c.accept=c.cq;})();
main=C;})();