"use strict";
var main; (function () {
    let Dm = 2463534242, D7 = () => { let x = Dm; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; Dm = x; return x; }, D = f => function () { return f(this); }, H = f => function (p1) { return f(this, p1); }, M = f => function (p1, p2) { return f(this, p1, p2); }, C8 = f => function (p1, p2, p3) { return f(this, p1, p2, p3, p3); }, Fe = f => function (p1, p2, p3, p4) { return f(this, p1, p2, p3, p4); }, DA = f => (args, callback) => { if (!args) { args = []; } let javaArgs = R(Y(), args.length); for (let i = 0; i < args.length; ++i) { javaArgs.data[i] = W(args[i]); } FI(() => { f.call(null, javaArgs); }, callback); }, Bm = target =>
        target.$clinit = () => { }, FO = obj => { let cls = obj.constructor; let arrayDegree = 0; while (cls.$meta && cls.$meta.item) { ++arrayDegree; cls = cls.$meta.item; } let clsName = ""; if (cls.$meta.primitive) { clsName = cls.$meta.name; } else { clsName = cls.$meta ? cls.$meta.name || "a/" + cls.name : "@" + cls.name; } while (arrayDegree-- > 0) { clsName += "[]"; } return clsName; }, F = superclass => { if (superclass === 0) { return function () { }; } if (superclass === void 0) { superclass = Y(); } return function () { superclass.call(this); }; }, BC = cls => B$(cls), Y = () => E, FP = () => {
            return {
                $array:
                    null, classObject: null, $meta: { supertypes: [], superclass: null }
            };
        }, BL = (name, binaryName) => { let cls = FP(); cls.$meta.primitive = true; cls.$meta.name = name; cls.$meta.binaryName = binaryName; cls.$meta.enum = false; cls.$meta.item = null; cls.$meta.simpleName = null; cls.$meta.declaringClass = null; cls.$meta.enclosingClass = null; return cls; }, Cb = BL("char", "C"), CQ = BL("int", "I"), DH = BL("void", "V");
    if (typeof BigInt !== 'function') { } else if (typeof BigInt64Array !== 'function') { } else { } let EC = (a, b) => a > b ? 1 : a < b ? -1 : a === b ? 0 : 1, Dd = Math.imul || function (a, b) { let ah = a >>> 16 & 0xFFFF; let al = a & 0xFFFF; let bh = b >>> 16 & 0xFFFF; let bl = b & 0xFFFF; return al * bl + (ah * bl + al * bh << 16 >>> 0) | 0; }, BI = (a, b) => (a >>> 0) / (b >>> 0) >>> 0, FQ = (a, b) => (a >>> 0) % (b >>> 0) >>> 0, BX = (a, b) => { a >>>= 0; b >>>= 0; return a < b ? -1 : a > b ? 1 : 0; };
    function Gb(lo, hi) { this.lo = lo | 0; this.hi = hi | 0; }
    if (typeof BigInt !== "function") { } else { } if (typeof BigInt !== 'function') {
        function Ge(lo, hi, sup) { this.lo = lo; this.hi = hi; this.sup = sup; }
    } else { } let R = (cls, sz) => { let data = new Array(sz); data.fill(null); return new (Br(cls))(data); };
    if (typeof BigInt64Array !== 'function') { } else { } let BA = sz => new Eu(new Uint16Array(sz)), E_ = sz => new ED(new Int32Array(sz)), Br = cls => {
        let result = cls.$array; if (result === null) {
            function JavaArray(data) { (Y()).call(this); this.data = data; } JavaArray.prototype = Object.create((Y()).prototype); JavaArray.prototype.type = cls; JavaArray.prototype.constructor = JavaArray; JavaArray.prototype.toString = function () { let str = "["; for (let i = 0; i < this.data.length; ++i) { if (i > 0) { str += ", "; } str += this.data[i].toString(); } str += "]"; return str; }; JavaArray.prototype.dc
                = function () { let dataCopy; if ('slice' in this.data) { dataCopy = this.data.slice(); } else { dataCopy = new this.data.constructor(this.data.length); for (let i = 0; i < dataCopy.length; ++i) { dataCopy[i] = this.data[i]; } } return new (Br(this.type))(dataCopy); }; let name = "[" + cls.$meta.binaryName; JavaArray.$meta = { item: cls, supertypes: [Y()], primitive: false, superclass: Y(), name: name, binaryName: name, enum: false, simpleName: null, declaringClass: null, enclosingClass: null }; JavaArray.classObject = null; JavaArray.$array = null; result = JavaArray; cls.$array
                    = JavaArray;
        } return result;
    }, BS, Eq = strings => { EO(); BS = new Array(strings.length); for (let i = 0; i < strings.length; ++i) { BS[i] = CC(W(strings[i])); } }, G = index => BS[index], Df = (array, offset, count) => { let result = ""; let limit = offset + count; for (let i = offset; i < limit; i = i + 1024 | 0) { let next = Math.min(limit, i + 1024 | 0); result += String.fromCharCode.apply(null, array.subarray(i, next)); } return result; }, W = str => str === null ? null : Cq(str), Bn = str => str === null ? null : str.cm, EO = () => Be(), CC;
    { CC = str => str; } let L = ex => { throw EP(ex); }, Bv = Symbol("javaException"), EP = ex => { let err = ex.$jsException; if (!err) { let javaCause = F0(ex); let jsCause = javaCause !== null ? javaCause.$jsException : void 0; let cause = typeof jsCause === "object" ? { cause: jsCause } : void 0; err = new U("Java exception thrown", cause); if (typeof Error.captureStackTrace === "function") { Error.captureStackTrace(err); } err[Bv] = ex; ex.$jsException = err; Fn(err, ex); } return err; }, Fn = (err, ex) => {
        if (typeof DV === "function" && err.stack) {
            let stack = DV(err.stack); let javaStack =
                R(Ee(), stack.length); let elem; let noStack = false; for (let i = 0; i < stack.length; ++i) { let element = stack[i]; elem = Et(W(element.className), W(element.methodName), W(element.fileName), element.lineNumber); if (elem == null) { noStack = true; break; } javaStack.data[i] = elem; } if (!noStack) { EH(ex, javaStack); }
        }
    }, U;
    if (typeof Reflect === 'object') {
        let defaultMessage = Symbol("defaultMessage"); U = function U(message, cause) { let self = Reflect.construct(Error, [void 0, cause], U); Object.setPrototypeOf(self, U.prototype); self[defaultMessage] = message; return self; }
            ; U.prototype = Object.create(Error.prototype, { constructor: { configurable: true, writable: true, value: U }, message: { get() { try { let javaException = this[Bv]; if (typeof javaException === 'object') { let javaMessage = Dw(javaException); if (typeof javaMessage === "object") { return javaMessage !== null ? javaMessage.toString() : null; } } return this[defaultMessage]; } catch (e) { return "Exception occurred trying to extract Java exception message: " + e; } } } });
    } else { U = Error; } let DI = e => e instanceof Error && typeof e[Bv] === 'object' ? e[Bv] : null, Dw = t => Dn(t), F0
        = t => Dq(t), Ee = () => Gj, Et = (className, methodName, fileName, lineNumber) => { { return null; } }, EH = (e, stack) => { }, Cl = null, EU = data => { let i = 0; let packages = new Array(data.length); for (let j = 0; j < data.length; ++j) { let prefixIndex = data[i++]; let prefix = prefixIndex >= 0 ? packages[prefixIndex] : ""; packages[j] = prefix + data[i++] + "."; } Cl = packages; }, Cr = data => {
            let packages = Cl; let i = 0; while (i < data.length) {
                let cls = data[i++]; cls.$meta = {}; let m = cls.$meta; let className = data[i++]; m.name = className !== 0 ? className : null; if (m.name !== null) {
                    let packageIndex
                        = data[i++]; if (packageIndex >= 0) { m.name = packages[packageIndex] + m.name; }
                } m.binaryName = "L" + m.name + ";"; let superclass = data[i++]; m.superclass = superclass !== 0 ? superclass : null; m.supertypes = data[i++]; if (m.superclass) { m.supertypes.push(m.superclass); cls.prototype = Object.create(m.superclass.prototype); } else { cls.prototype = {}; } let flags = data[i++]; m.enum = (flags & 8) !== 0; m.flags = flags; m.primitive = false; m.item = null; cls.prototype.constructor = cls; cls.classObject = null; m.accessLevel = data[i++]; let innerClassInfo = data[i++]; if (innerClassInfo
                    === 0) { m.simpleName = null; m.declaringClass = null; m.enclosingClass = null; } else { let enclosingClass = innerClassInfo[0]; m.enclosingClass = enclosingClass !== 0 ? enclosingClass : null; let declaringClass = innerClassInfo[1]; m.declaringClass = declaringClass !== 0 ? declaringClass : null; let simpleName = innerClassInfo[2]; m.simpleName = simpleName !== 0 ? simpleName : null; } let clinit = data[i++]; cls.$clinit = clinit !== 0 ? clinit : function () { }; let virtualMethods = data[i++]; if (virtualMethods !== 0) {
                        for (let j = 0; j < virtualMethods.length; j += 2) {
                            let name = virtualMethods[j]; let func
                                = virtualMethods[j + 1]; if (typeof name === 'string') { name = [name]; } for (let k = 0; k < name.length; ++k) { cls.prototype[name[k]] = func; }
                        }
                    } cls.$array = null;
            }
        }, FI = (runner, callback) => { let result; try { result = runner(); } catch (e) { result = e; } if (typeof callback !== 'undefined') { callback(result); } else if (result instanceof Error) { throw result; } };
    function E() { this.$id$ = 0; }
    let I = a => { return; }, Gi = () => { let a = new E(); I(a); return a; }, Cd = a => { return B$(a.constructor); }, D1 = (a, b) => { return a !== b ? 0 : 1; }, CO = a => { let b, c; b = FE(Co(a)); c = Bw(); O(O(c, G(0)), b); return Bg(c); }, Co = a => { let b; b = a; if (!b.$id$) b.$id$ = D7(); return a.$id$; };
    function Bk() { let a = this; E.call(a); a.c9 = null; a.c7 = null; a.cZ = 0; a.db = 0; }
    let Dc = a => { a.cZ = 1; a.db = 1; a.g(); }, Ga = () => { let a = new Bk(); Dc(a); return a; }, CK = (a, b) => { a.cZ = 1; a.db = 1; a.g(); a.c9 = b; }, Gh = a => { let b = new Bk(); CK(b, a); return b; }, EF = a => { return a; }, Dn = a => { return a.c9; }, Dq = a => { return a.c7 === a ? null : a.c7; }, Bj = F(Bk), BW = a => { Dc(a); }, F9 = () => { let a = new Bj(); BW(a); return a; }, BQ = (a, b) => { CK(a, b); }, Gg = a => { let b = new Bj(); BQ(b, a); return b; }, K = F(Bj), T = a => { BW(a); }, F$ = () => { let a = new K(); T(a); return a; }, BJ = (a, b) => { BQ(a, b); }, Gf = a => { let b = new K(); BJ(b, a); return b; }, Bu = F(K), BY = a => { T(a); }, Dj = () => { let a = new Bu(); BY(a); return a; }, C0
        = F(K), Cu = a => { T(a); }, DN = () => { let a = new C0(); Cu(a); return a; }, F4 = F(), FJ = (b, c) => { let d, e, f, g; d = b.data; e = BA(c); f = Bz(c, d.length); g = 0; while (g < f) { e.data[g] = d[g]; g = g + 1 | 0; } return e; }, Eb = (b, c) => { let d, e, f, g; d = b.data; e = EQ((Cd(b)).l(), c); f = Bz(c, d.length); g = 0; while (g < f) { e.data[g] = d[g]; g = g + 1 | 0; } return e; }, ER = (b, c, d, e) => { let f, g; if (c > d) L(BT()); while (c < d) { f = b.data; g = c + 1 | 0; f[c] = e; c = g; } }, E3 = F(), EQ = (b, c) => { if (b === null) L(Eh()); if (b === BC(DH)) L(BT()); if (c < 0) L(DB()); return DY(b.n(), c); }, DY = (b, c) => {
            if (b.$meta.primitive) { switch (b) { }; } return R(b,
                c);
        };
    function C9() { let a = this; E.call(a); a.cq = null; a.cn = 0; a.cl = 0; a.cu = 0; a.cy = 0; a.cO = 0; a.cK = 0; a.cJ = 0; a.cL = 0; a.cN = 0; }
    let Dl = (a, b, c, d, e, f) => { I(a); a.cO = (-1); a.cq = b; a.cn = c; a.cl = d; a.cu = e; a.cy = f; a.cK = 0; a.cJ = 0; a.cL = e; a.cN = f; }, Q = (a, b, c, d, e) => { let f = new C9(); Dl(f, a, b, c, d, e); return f; }, F3 = (a, b, c) => { a.cK = b; a.cJ = c; a.cL = a.cu - (b * 2 | 0) | 0; a.cN = a.cy - (c * 2 | 0) | 0; return a; }, D8 = (a, b, c, d, e) => { a.cK = b; a.cJ = c; a.cL = d; a.cN = e; return a; }, DZ = (b, c) => { let d, e, f, g; d = b.cn + b.cK | 0; e = b.cl + b.cJ | 0; f = c.cn + c.cK | 0; g = c.cl + c.cJ | 0; return d < (f + c.cL | 0) && f < (d + b.cL | 0) && e < (g + c.cN | 0) && g < (e + b.cN | 0) ? 1 : 0; }, CX = F(0), BE = F(0), BF = F(), Du = a => { I(a); }, DX = a => { return a.o() ? 0 : 1; }, El = (a, b) => { let c, d; c = a.p(); while (c.q()) { d = c.r(); if (F8(d, b)) return 1; } return 0; }, F5 = (a, b) => { let c, d, e; Ep(b); c = 0; d = a.p(); while (d.q()) { e = d.r(); if (b.u(e)) { d.v(); c = 1; } } return c; }, C$ = F(0), CG = F(0);
    function BK() { BF.call(this); this.cv = 0; }
    let CB = a => { Du(a); }, Eo = a => { return FL(a); }, Bl = F(0), B6 = F(), Bt = F(0), CD = F(B6), Es = null, BB = () => { BB = Bm(CD); D6(); }, FE = b => { BB(); return D_(b, 4); }, FU = b => { let c, d, e; BB(); if (!b) return 32; c = 0; d = b >>> 16 | 0; if (d) c = 16; else d = b; e = d >>> 8 | 0; if (!e) e = d; else c = c | 8; d = e >>> 4 | 0; if (!d) d = e; else c = c | 4; e = d >>> 2 | 0; if (!e) e = d; else c = c | 2; if (e >>> 1 | 0) c = c | 1; return (32 - c | 0) - 1 | 0; }, D6 = () => { Es = BC(CQ); }, BN = F(K), CE = (a, b) => { BJ(a, b); }, Fa = a => { let b = new BN(); CE(b, a); return b; }, C2 = a => { T(a); }, Eh = () => { let a = new BN(); C2(a); return a; }, FY = F(), J = b => {
        let c, d, e, f, g, h; c
            = b.y(47); d = c < 0 ? b : b.z(c + 1 | 0); e = d.y(46); if (e >= 0) d = d.A(0, e); f = window.document; g = Bw(); O(O(g, G(1)), d); d = f.getElementById(Bn(Bg(g))); if (d === null) { d = f.createElement("img"); g = b.z(b.y(47) + 1 | 0); h = Bw(); O(O(h, G(2)), g); d.src = Bn(Bg(h)); } return d;
    }, BU = F(), Er = null, EG = null, Bh = () => { Bh = Bm(BU); Fh(); }, FS = b => { let c; Bh(); c = b - 65536 | 0; return (55296 | c >> 10 & 1023) & 65535; }, FA = b => { Bh(); return (56320 | b & 1023) & 65535; }, B7 = (b, c) => { Bh(); if (c >= 2 && c <= 36 && b >= 0 && b < c) return b < 10 ? (48 + b | 0) & 65535 : ((97 + b | 0) - 10 | 0) & 65535; return 0; }, Fh = () => {
        Er = BC(Cb); EG = R(BU,
            128);
    }, FW = F(), D_ = (b, c) => { let d, e, f, g, h, i, j, k; if (!b) return G(3); d = 1 << c; e = d - 1 | 0; f = (((32 - FU(b) | 0) + c | 0) - 1 | 0) / c | 0; g = BA(f); h = Dd(f - 1 | 0, c); i = 0; while (h >= 0) { j = g.data; k = i + 1 | 0; j[i] = B7((b >>> h | 0) & e, d); h = h - c | 0; i = k; } return DR(g); }, DU = F(), Bx = () => { return Fp(); }, Fp = () => { return Math.random(); }, Bz = (b, c) => { if (b < c) c = b; return c; }, Bs = (b, c) => { if (b > c) c = b; return c; }, F1 = F();
    function Cf() { E.call(this); this.cp = null; }
    let B_ = (a, b) => { I(a); a.cp = b; }, EJ = a => { let b = new Cf(); B_(b, a); return b; }, Ef = (a, b) => {
        let c, d, e, f, g; c = "#f7f7f7"; b.fillStyle = c; b.fillRect(0.0, 0.0, 750.0, 250.0); c = (a.cp.F()).p(); while (c.q()) { d = c.r(); if (d.cq !== null) b.drawImage(d.cq, d.cn, d.cl, d.cu, d.cy); } e = a.cp.G(); if (e !== null) { b.drawImage(e, a.cp.H(), 224.0, 750.0, 26.0); b.drawImage(e, a.cp.I(), 224.0, 750.0, 26.0); } f = a.cp.J(); if (f.cq !== null) b.drawImage(f.cq, f.cn, f.cl, f.cu, f.cy); c = (a.cp.K()).p(); while (c.q()) { g = c.r(); if (g.cq !== null) b.drawImage(g.cq, g.cn, g.cl, g.cu, g.cy); } Fu(a,
            b); if (a.cp.M()) EV(a, b);
    }, Fu = (a, b) => { let c, d, e, f; c = "#555555"; b.fillStyle = c; c = "bold 18px Courier, monospace"; b.font = c; d = a.cp.O(); e = a.cp.P(); c = Bw(); B3(O(B3(O(c, G(4)), d), G(5)), e); f = Bg(c); b.fillText(Bn(f), 550.0, 25.0); }, EV = (a, b) => { let c, d; c = a.cp.R(); d = a.cp.S(); if (c !== null) { b.drawImage(c, 184.0, 85.0, 382.0, 21.0); b.drawImage(d, 357.0, 121.0, 36.0, 32.0); } }, Dh = F(0), Fq = F(), Bc = (b, c) => {
        let name = 'jso$functor$' + c; let result = b[name]; if (typeof result !== 'function') {
            let fn = function () { return b[c].apply(b, arguments); }; result = () => fn; b[name]
                = result;
        } return result();
    }, Bb = F(0), B8 = F(0), BH = F(), CU = a => { I(a); }, Fd = () => { let a = new BH(); CU(a); return a; }, Fb = (a, b) => { DC(b); }, D4 = (a, b) => { a.U(Ct(b)); }, BP = F(0), CL = F(Bu), CV = a => { BY(a); }, B5 = () => { let a = new CL(); CV(a); return a; }, CH = F(), P = null, Dp = null, Ce = null, Z = () => { Z = Bm(CH); E8(); }, FK = b => {
        let c, d, e, f, g; Z(); c = window; d = c.document; e = d.getElementById("gameCanvas"); f = 750; e.width = f; f = 250; e.height = f; Ce = e.getContext("2d"); P = Dx(); Dp = EJ(P); g = Fc(); d.addEventListener("keydown", Bc(g, "handleEvent")); g = FF(); d.addEventListener("keyup",
            Bc(g, "handleEvent")); g = F7(); (function (_g) { let _last = 0, _acc = 0, _step = 1000 / 60; (function _raf(ts) { ts = ts || performance.now(); _acc += ts - (_last || ts); _last = ts; while (_acc >= _step) { Bc(_g, "onTimer")(); _acc -= _step; } _acc = Math.min(_acc, _step); requestAnimationFrame(_raf); })(); })(g); g = Ft(); setInterval(Bc(g, "onTimer"), 1500);
    }, Ec = () => { Z(); P.Y(); }, EK = () => { Z(); P.Z(); Dp.ba(Ce); }, Fz = b => { Z(); if (G(6).bb(W(b.code))) P.bc(); }, FZ = b => { let c, d; Z(); c = b; d = W(c.code); if (!(!d.bd(G(7)) && !G(8).bb(d))) b.preventDefault(); if (P.M()) { if (!(!G(9).bb(d) && !G(8).bb(d))) P.be(); return; } if (!(!G(10).bb(d) && !G(8).bb(d))) P.bf(); if (G(6).bb(d)) P.bg(); }, E8 = () => { return; }, E0 = F(), F8 = (b, c) => { if (b === c) return 1; return b !== null ? b.bb(c) : c !== null ? 0 : 1; }, Ep = b => { return Em(b, G(11)); }, Em
            = (b, c) => { if (b !== null) return b; L(Fa(c)); }, Fm = (b, c, d) => { if (b >= 0 && c >= 0 && c <= (d - b | 0)) return b; L(Dj()); }, Ei = F(), Ci = F(0), BR = F(0);
    function Bo() { let a = this; E.call(a); a.ck = null; a.cr = 0; }
    let BM = a => { B4(a, 16); }, Gd = () => { let a = new Bo(); BM(a); return a; }, B4 = (a, b) => { I(a); a.ck = BA(b); }, F_ = a => { let b = new Bo(); B4(b, a); return b; }, Cw = (a, b) => { return a.bj(a.cr, b); }, Cc = (a, b, c) => { let d, e, f; if (b >= 0 && b <= a.cr) { if (c === null) c = G(12); else if (c.bk()) return a; a.bl(a.cr + c.bm() | 0); d = a.cr - 1 | 0; while (d >= b) { a.ck.data[d + c.bm() | 0] = a.ck.data[d]; d = d + (-1) | 0; } a.cr = a.cr + c.bm() | 0; d = 0; while (d < c.bm()) { e = a.ck.data; f = b + 1 | 0; e[b] = c.bn(d); d = d + 1 | 0; b = f; } return a; } L(B5()); }, Cm = (a, b) => { return a.bo(b, 10); }, Fr = (a, b, c) => { return a.bp(a.cr, b, c); }, D9
        = (a, b, c, d) => { let e, f, g, h, i, j, k, l; e = 1; if (c < 0) { e = 0; c = -c | 0; } a: { if (BX(c, d) < 0) { if (e) B9(a, b, b + 1 | 0); else { B9(a, b, b + 2 | 0); f = a.ck.data; g = b + 1 | 0; f[b] = 45; b = g; } a.ck.data[b] = B7(c, d); } else { h = 1; i = 1; j = BI((-1), d); b: { while (true) { k = Dd(h, d); if (BX(k, c) > 0) { k = h; break b; } i = i + 1 | 0; if (BX(k, j) > 0) break; h = k; } } if (!e) i = i + 1 | 0; B9(a, b, b + i | 0); if (e) l = b; else { f = a.ck.data; l = b + 1 | 0; f[b] = 45; } while (true) { if (!k) break a; f = a.ck.data; g = l + 1 | 0; f[l] = B7(BI(c, k), d); c = FQ(c, k); k = BI(k, d); l = g; } } } return a; }, CF = (a, b, c) => { return a.br(b, c === null ? G(12) : c.f()); }, Cg = (a, b) => { let c; if (a.ck.data.length >= b) return; c = a.ck.data.length >= 1073741823 ? 2147483647 : Bs(b, Bs(a.ck.data.length * 2 | 0, 5)); a.ck = FJ(a.ck, c); }, CS = a => { return EW(a.ck, 0, a.cr); }, B9 = (a, b, c) => { let d, e; d = a.cr - b | 0; a.bl((a.cr + c | 0) - b | 0); e = d - 1 | 0; while (e >= 0) { a.ck.data[c + e | 0] = a.ck.data[b + e | 0]; e = e + (-1) | 0; } a.cr = a.cr + (c - b | 0) | 0; }, Dt = F(0), Cv = F(Bo), CN = a => { BM(a); }, Bw = () => { let a = new Cv(); CN(a); return a; }, O = (a, b) => { Cw(a, b); return a; }, B3 = (a, b) => { Cm(a, b); return a; }, E5 = (a, b, c) => { CF(a, b, c); return a; }, Fj = (a, b, c) => { Cc(a, b, c); return a; }, Bg = a => { return CS(a); }, Fw
            = (a, b) => { Cg(a, b); }, Ew = (a, b, c) => { return a.bx(b, c); }, FN = (a, b, c) => { return a.by(b, c); }, B2 = F(), Ca = a => { I(a); }, Ft = () => { let a = new B2(); Ca(a); return a; }, FH = a => { Ec(); }, DO = a => { a.bA(); }, B1 = F(), C4 = a => { I(a); }, F7 = () => { let a = new B1(); C4(a); return a; }, Ex = a => { EK(); }, EE = a => { a.bA(); }, C7 = F(K), C_ = a => { T(a); }, En = () => { let a = new C7(); C_(a); return a; };
    function Cs() { let a = this; E.call(a); a.cQ = null; a.c2 = null; a.c8 = null; a.c0 = null; a.cR = null; a.c3 = null; a.c4 = null; a.c5 = null; a.c_ = null; a.c$ = null; a.da = null; a.cW = null; a.c6 = null; a.cX = null; a.c1 = null; a.cj = null; a.cs = null; a.cw = null; a.cC = 0; a.cT = 0; a.cB = 0; a.cA = 0; a.cG = 0; a.cI = 0; a.cx = 0; a.cU = 0; a.cD = 0; a.cE = 0; a.cM = 0; }
    let Cx = a => { let b, c, d; I(a); a.cs = Bq(); a.cw = Bq(); b = R(Bd, 2); c = b.data; c[0] = Ba(J(G(13))); c[1] = Ba(J(G(14))); a.cQ = b; a.c2 = J(G(15)); a.c8 = J(G(16)); b = R(Bd, 2); c = b.data; c[0] = Ba(J(G(17))); c[1] = Ba(J(G(18))); a.c0 = b; b = R(Bd, 2); c = b.data; c[0] = Ba(J(G(19))); c[1] = Ba(J(G(20))); a.cR = b; a.c3 = J(G(21)); a.c4 = J(G(22)); a.c5 = J(G(23)); a.c_ = J(G(24)); a.c$ = J(G(25)); a.da = J(G(26)); a.cW = J(G(27)); a.c6 = J(G(28)); a.cX = J(G(29)); a.c1 = J(G(30)); a.cC = 156; a.cT = 190; d = Q(V(a.cQ.data[0]), 50, a.cC, 88, 94); a.cj = d.bG(20, 38, 48, 56); Cy(a); }, Dx = () => { let a = new Cs(); Cx(a); return a; }, Cy
        = a => { a.cs.bI(); a.cw.bI(); a.cj.cq = V(a.cQ.data[0]); a.cj.cn = 50; a.cj.cl = a.cC; a.cj.cu = 88; a.cj.cy = 94; a.cj.bG(20, 38, 48, 56); a.cB = 0; a.cA = 750; a.cG = 0; a.cI = 8; a.cx = 0; a.cD = 0; a.cE = 0; a.cM = 0; Dk(a); }, DQ = a => { Cy(a); }, Fk = a => { if (!a.cD && !a.cE) { if (a.cj.cl == a.cC) { a.cG = (-18); a.cj.cq = a.c8; } return; } }, Fy = a => { if (!a.cD && a.cj.cl == a.cC) { a.cE = 1; a.cj.cu = 118; a.cj.cy = 60; a.cj.cl = a.cT; a.cj.bG(20, 10, 78, 40); return; } }, Fl = a => { if (!a.cE) return; a.cE = 0; a.cj.cu = 88; a.cj.cy = 94; a.cj.cl = a.cC; a.cj.bG(20, 38, 48, 56); }, FG = a => {
            if (a.cD) return; a.cM = a.cM + 1 | 0; a.cI = Bz(8
                + (a.cx / 500 | 0) | 0, 20); EL(a); Fi(a); Ff(a); DF(a); a.cx = a.cx + 1 | 0;
        }, EL = a => { a.cB = a.cB - a.cI | 0; a.cA = a.cA - a.cI | 0; if ((a.cB + 750 | 0) <= 0) a.cB = a.cA + 750 | 0; if ((a.cA + 750 | 0) <= 0) a.cA = a.cB + 750 | 0; }, Fi = a => { let b, c, d; b = Bq(); c = a.cw.p(); while (c.q()) { d = c.r(); d.cn = d.cn - (a.cI / 2 | 0) | 0; if ((d.cn + d.cu | 0) < 0) b.bO(d); } a.cw.bP(b); if (!(!a.cw.bk() && (a.cw.bQ(a.cw.o() - 1 | 0)).cn >= 550)) Dk(a); }, Dk = a => { let b; b = 30 + (Bx() * 60.0 | 0) | 0; a.cw.bO(Q(a.c6, 750, b, 92, 28)); }, Ff = a => {
            let b, c, d; b = !a.cE ? a.cC : a.cT; c = a.cj; c.cl = c.cl + a.cG | 0; if (a.cj.cl < b) a.cG = a.cG + 1 | 0; else {
                a.cj.cl
                    = b; a.cG = 0; d = (a.cM / 8 | 0) % 2 | 0; a.cj.cq = !a.cE ? V(a.cQ.data[d]) : V(a.c0.data[d]);
            }
        }, DF = a => { let b, c, d; b = Bq(); c = a.cs.p(); while (c.q()) { d = c.r(); d.cn = d.cn - a.cI | 0; if (d.cO >= 0) { d.cO = (a.cM / 8 | 0) % 2 | 0; d.cq = V(a.cR.data[d.cO]); } if (DZ(d, a.cj)) { a.cj.cq = a.c2; a.cD = 1; if (a.cx > a.cU) a.cU = a.cx; return; } if ((d.cn + d.cu | 0) < 0) b.bO(d); } a.cs.bP(b); }, D2 = a => { let b, c; if (a.cD) return; b = Bx(); if (a.cx > 500 && b < 0.25) { E$(a); return; } c = Bx() >= 0.3 ? 0 : 1; if (!c) Fs(a, b); else FX(a, b); }, E$ = a => {
            let b, c, d, e; b = E_(3); c = b.data; c[0] = 150; c[1] = 100; c[2] = 50; d = c[Bx() * c.length | 0]; e
                = (Q(V(a.cR.data[0]), 750, d, 92, 80)).bW(15, 15); e.cO = 0; a.cs.bO(e);
        }, Fs = (a, b) => { let c; c = 180; if (b < 0.33) a.cs.bO((Q(a.c3, 750, c, 34, 70)).bW(5, 5)); else if (b >= 0.66) a.cs.bO((Q(a.c5, 750, c, 103, 70)).bW(5, 5)); else a.cs.bO((Q(a.c4, 750, c, 69, 70)).bW(5, 5)); }, FX = (a, b) => { let c; c = 150; if (b < 0.33) a.cs.bO((Q(a.c_, 750, c, 49, 100)).bW(8, 5)); else if (b >= 0.66) a.cs.bO((Q(a.da, 750, c, 147, 100)).bW(8, 5)); else a.cs.bO((Q(a.c$, 750, c, 98, 100)).bW(8, 5)); }, DW = a => { return a.cj; }, FB = a => { return a.cs; }, ES = a => { return a.cw; }, DT = a => { return a.cB; }, Dv = a => { return a.cA; }, DK
            = a => { return a.cW; }, E4 = a => { return a.cX; }, E6 = a => { return a.c1; }, Ed = a => { return a.cx; }, DL = a => { return a.cU; }, EN = a => { return a.cD; }, BV = F(0), B0 = F(), CT = a => { I(a); }, FF = () => { let a = new B0(); CT(a); return a; }, Fx = (a, b) => { Fz(b); }, E1 = (a, b) => { a.bY(b); }, CW = F(0), BZ = F(), CP = a => { I(a); }, Fc = () => { let a = new BZ(); CP(a); return a; }, FD = (a, b) => { FZ(b); }, D5 = (a, b) => { a.bY(b); }, EM = F(K);
    function Bd() { E.call(this); this.cY = null; }
    let Ej = null, By = null, Bf = null, Bp = null, Dr = null, Cj = null, CR = null, S = () => { S = Bm(Bd); E2(); }, Ek = (a, b) => { S(); I(a); a.cY = b; }, Bi = a => { let b = new Bd(); Ek(b, a); return b; }, Ba = b => {
        let c, d, e, f, g, h, i, j, k; S(); if (b === null) return null; c = b; d = W(typeof c); e = !d.bb(G(31)) && !d.bb(G(32)) ? 0 : 1; if (e && b[X] === true) return b; if (By !== null) {
            if (e) { f = By.get(c); g = (typeof f == 'undefined' ? 1 : 0) ? void 0 : f.deref(); if (!(typeof g == 'undefined' ? 1 : 0)) return g; h = Bi(c); By.set(c, new WeakRef(h)); return h; } if (d.bb(G(33))) {
                i = c; f = Bf.get(i); g = (typeof f == 'undefined' ? 1 : 0)
                    ? void 0 : f.deref(); if (!(typeof g == 'undefined' ? 1 : 0)) return g; h = Bi(c); j = h; Bf.set(i, new WeakRef(j)); Dg(Cj, j, i); return h;
            } if (d.bb(G(34))) { k = c; f = Bp.get(k); g = (typeof f == 'undefined' ? 1 : 0) ? void 0 : f.deref(); if (!(typeof g == 'undefined' ? 1 : 0)) return g; h = Bi(c); j = h; Bp.set(k, new WeakRef(j)); Dg(CR, j, k); return h; } if (d.bb(G(35))) { f = Dr; g = f === null ? void 0 : f.deref(); if (!(typeof g == 'undefined' ? 1 : 0)) return g; h = Bi(c); j = h; Dr = new WeakRef(j); return h; }
        } return Bi(c);
    }, V = b => { S(); if (b === null) return null; return b[X] === true ? b : b.cY; }, Ct = b => {
        S(); if
            (b === null) return null; return b instanceof Y() ? b : Ba(b);
    }, DJ = b => { let c, d; S(); c = Bp; d = V(b); c.delete(d); }, DC = b => { let c, d; S(); c = Bf; d = V(b); c.delete(d); }, E2 = () => {
        let b, c; Ej = new WeakMap(); b = !(typeof WeakRef !== 'undefined' ? 1 : 0) ? null : new WeakMap(); By = b; b = !(typeof WeakRef !== 'undefined' ? 1 : 0) ? null : new Map(); Bf = b; b = !(typeof WeakRef !== 'undefined' ? 1 : 0) ? null : new Map(); Bp = b; if (Bf === null) b = null; else { c = Fd(); b = new FinalizationRegistry(Bc(c, "accept")); } Cj = b; if (Bp === null) b = null; else { c = DS(); b = new FinalizationRegistry(Bc(c, "accept")); } CR
            = b;
    }, Dg = (b, c, d) => { return b.register(c, d); }, Cn = F(0);
    function BD() { let a = this; BK.call(a); a.co = null; a.ct = 0; }
    let C3 = a => { BO(a, 10); }, Bq = () => { let a = new BD(); C3(a); return a; }, BO = (a, b) => { CB(a); if (b >= 0) { a.co = R(E, b); return; } L(BT()); }, Gc = a => { let b = new BD(); BO(b, a); return b; }, Fg = (a, b) => { let c; if (a.co.data.length < b) { c = a.co.data.length >= 1073741823 ? 2147483647 : Bs(b, Bs(a.co.data.length * 2 | 0, 5)); a.co = Eb(a.co, c); } }, Fv = (a, b) => { Cz(a, b); return a.co.data[b]; }, DD = a => { return a.ct; }, Dy = (a, b) => { let c, d; a.bl(a.ct + 1 | 0); c = a.co.data; d = a.ct; a.ct = d + 1 | 0; c[d] = b; a.cv = a.cv + 1 | 0; return 1; }, FR = (a, b) => {
        let c, d, e, f; Cz(a, b); c = a.co.data[b]; a.ct = a.ct - 1 | 0; while
            (b < a.ct) { d = a.co.data; e = a.co.data; f = b + 1 | 0; d[b] = e[f]; b = f; } a.co.data[a.ct] = null; a.cv = a.cv + 1 | 0; return c;
    }, DM = a => { ER(a.co, 0, a.ct, null); a.ct = 0; a.cv = a.cv + 1 | 0; }, Cz = (a, b) => { if (b >= 0 && b < a.ct) return; L(Dj()); }, Ey = F(), EI = b => { return b.$meta.item; }, N = F(), DE = null, CI = null, D$ = null, Be = () => { Be = Bm(N); FC(); }, CM = a => { Be(); I(a); a.cm = ""; }, FT = () => { let a = new N(); CM(a); return a; }, C1 = (a, b) => { let c; Be(); c = b.data; I(a); a.cm = Df(b.data, 0, c.length); }, DR = a => { let b = new N(); C1(b, a); return b; }, Db = (a, b) => { a.cm = b; }, Cq = a => { let b = new N(); Db(b, a); return b; }, Do
            = (a, b, c, d) => { let e; Be(); e = b.data; I(a); Fm(c, d, e.length); a.cm = Df(b.data, c, d); }, EW = (a, b, c) => { let d = new N(); Do(d, a, b, c); return d; }, FV = (a, b) => { if (b >= 0 && b < a.cm.length) return a.cm.charCodeAt(b); L(B5()); }, E7 = a => { return a.cm.length; }, ET = a => { return a.cm.length ? 0 : 1; }, Eg = (a, b, c) => { let d, e, f; if ((c + b.bm() | 0) > a.bm()) return 0; d = 0; while (d < b.bm()) { e = b.bn(d); f = c + 1 | 0; if (e != a.bn(c)) return 0; d = d + 1 | 0; c = f; } return 1; }, EY = (a, b) => { if (a === b) return 1; return a.b6(b, 0); }, F2 = (a, b, c) => {
                let d, e, f, g, h; d = Bz(c, a.bm() - 1 | 0); if (b < 65536) {
                    e = b & 65535; while
                        (true) { if (d < 0) return (-1); if (a.cm.charCodeAt(d) == e) break; d = d + (-1) | 0; } return d;
                } f = FS(b); g = FA(b); while (true) { if (d < 1) return (-1); if (a.cm.charCodeAt(d) == g) { h = d - 1 | 0; if (a.cm.charCodeAt(h) == f) break; } d = d + (-1) | 0; } return h;
            }, D3 = (a, b) => { return a.b9(b, a.bm() - 1 | 0); }, EB = (a, b, c) => { let d, e; d = a.cm.length; e = EC(b, c); if (!e) return CI; if (!b && c == d) return a; if (b >= 0 && e <= 0 && c <= d) return Cq(a.cm.substring(b, c)); L(B5()); }, Ea = (a, b) => { return a.A(b, a.bm()); }, Ez = a => { return a; }, F6 = (a, b) => {
                let c; if (a === b) return 1; if (!(b instanceof N)) return 0; c
                    = b; return a.cm !== c.cm ? 0 : 1;
            }, FC = () => { DE = BA(0); CI = FT(); D$ = DP(); }, BG = F(), C5 = a => { I(a); }, DS = () => { let a = new BG(); C5(a); return a; }, Ev = (a, b) => { DJ(b); }, FM = (a, b) => { a.U(Ct(b)); }, Ds = F(K), Ch = a => { T(a); }, DB = () => { let a = new Ds(); Ch(a); return a; }, E9 = F(), Di = F(0), CY = F(K), CA = a => { T(a); };
    let BT = () => { let a = new CY(); CA(a); return a; };
    function De() { let a = this; E.call(a); a.cF = 0; a.cV = 0; a.cP = 0; a.cH = 0; a.cz = null; }
    let Cp = (a, b) => { a.cz = b; I(a); a.cV = a.cz.cv; a.cP = a.cz.o(); a.cH = (-1); }, FL = a => { let b = new De(); Cp(b, a); return b; }, EZ = a => { return a.cF >= a.cP ? 0 : 1; }, Fo = a => { let b, c; Da(a); a.cH = a.cF; b = a.cz; c = a.cF; a.cF = c + 1 | 0; return b.bQ(c); }, Dz = a => { if (a.cH < 0) L(DN()); Da(a); a.cz.cb(a.cH); a.cV = a.cz.cv; if (a.cH < a.cF) a.cF = a.cF - 1 | 0; a.cP = a.cP - 1 | 0; a.cH = (-1); }, Da = a => { if (a.cV >= a.cz.cv) return; L(En()); };
    function C6() { E.call(this); this.cS = null; }
    let EA = (a, b) => { let c; I(a); a.cS = b; c = a; b.classObject = c; }, EX = a => { let b = new C6(); EA(b, a); return b; }, B$ = b => { let c; if (b === null) return null; c = b.classObject; if (c === null) c = EX(b); return c; }, DG = a => { return a.cS; }, D0 = a => { return B$(EI(a.cS)); }, CJ = F(0), CZ = F(), Ck = a => { I(a); }, DP = () => { let a = new CZ(); Ck(a); return a; };
    EU([]);
    Cr([E, 0, 0, [], 0, 3, 0, 0, ["k", D(Cd), "bb", H(D1), "f", D(CO), "c", D(Co)], Bk, 0, E, [], 0, 3, 0, 0, ["g", D(EF), "ce", D(Dn), "cf", D(Dq)], Bj, 0, Bk, [], 0, 3, 0, 0, ["d", D(BW), "h", H(BQ)], K, 0, Bj, [], 0, 3, 0, 0, ["d", D(T), "h", H(BJ)], Bu, 0, K, [], 0, 3, 0, 0, ["d", D(BY)], C0, 0, K, [], 0, 3, 0, 0, ["d", D(Cu)], F4, 0, E, [], 0, 3, 0, 0, 0, E3, 0, E, [], 4, 3, 0, 0, 0, C9, 0, E, [], 0, 3, 0, 0, ["bE", function (b, c, d, e, f) { Dl(this, b, c, d, e, f); }, "bW", M(F3), "bG", Fe(D8)], CX, 0, E, [], 3, 3, 0, 0, 0, BE, 0, E, [CX], 3, 3, 0, 0, 0, BF, 0, E, [BE], 1, 3, 0, 0, ["d", D(Du), "bk", D(DX), "u", H(El), "bP", H(F5)], C$, 0, E, [BE], 3, 3, 0, 0, 0, CG,
        0, E, [C$], 3, 3, 0, 0, 0, BK, 0, BF, [CG], 1, 3, 0, 0, ["d", D(CB), "p", D(Eo)], Bl, 0, E, [], 3, 3, 0, 0, 0, B6, 0, E, [Bl], 1, 3, 0, 0, 0, Bt, 0, E, [], 3, 3, 0, 0, 0, CD, 0, B6, [Bt], 0, 3, 0, BB, 0, BN, 0, K, [], 0, 3, 0, 0, ["h", H(CE), "d", D(C2)], FY, 0, E, [], 4, 3, 0, 0, 0, BU, 0, E, [Bt], 0, 3, 0, Bh, 0, FW, 0, E, [], 4, 3, 0, 0, 0, DU, 0, E, [], 4, 3, 0, 0, 0, F1, 0, E, [], 4, 3, 0, 0, 0, Cf, 0, E, [], 0, 3, 0, 0, ["W", H(B_), "ba", H(Ef)], Dh, 0, E, [], 3, 3, 0, 0, 0, Fq, 0, E, [], 4, 0, 0, 0, 0, Bb, 0, E, [], 3, 3, 0, 0, 0, B8, 0, E, [Bb], 3, 3, 0, 0, 0, BH, 0, E, [B8], 0, 3, 0, 0, ["d", D(CU), "U", H(Fb), "cg", H(D4)], BP, 0, E, [], 3, 3, 0, 0, 0, CL, 0, Bu, [], 0, 3, 0, 0, ["d", D(CV)], CH,
        0, E, [], 0, 3, 0, Z, 0, E0, 0, E, [], 4, 3, 0, 0, 0, Ei, 0, E, [Bb], 0, 3, 0, 0, 0, Ci, 0, E, [], 3, 3, 0, 0, 0, BR, 0, E, [Bb], 3, 3, 0, 0, 0, Bo, 0, E, [Bl, BP], 0, 0, 0, 0, ["d", D(BM), "bi", H(B4), "bv", H(Cw), "br", M(Cc), "bw", H(Cm), "bo", M(Fr), "bp", C8(D9), "bj", M(CF), "bl", H(Cg), "f", D(CS)], Dt, 0, E, [], 3, 3, 0, 0, 0, Cv, 0, Bo, [Dt], 0, 3, 0, 0, ["d", D(CN), "e", H(O), "Q", H(B3), "bx", M(E5), "by", M(Fj), "f", D(Bg), "bl", H(Fw), "bj", M(Ew), "br", M(FN)], B2, 0, E, [BR], 0, 3, 0, 0, ["d", D(Ca), "bA", D(FH), "ch", D(DO)], B1, 0, E, [BR], 0, 3, 0, 0, ["d", D(C4), "bA", D(Ex), "ch", D(EE)], C7, 0, K, [], 0, 3, 0, 0, ["d", D(C_)], Cs,
        0, E, [], 0, 3, 0, 0, ["d", D(Cx), "be", D(DQ), "bf", D(Fk), "bg", D(Fy), "bc", D(Fl), "Z", D(FG), "Y", D(D2), "J", D(DW), "K", D(FB), "F", D(ES), "H", D(DT), "I", D(Dv), "G", D(DK), "R", D(E4), "S", D(E6), "P", D(Ed), "O", D(DL), "M", D(EN)], BV, 0, E, [Bb], 3, 3, 0, 0, 0, B0, 0, E, [BV], 0, 3, 0, 0, ["d", D(CT), "bY", H(Fx), "ci", H(E1)], CW, 0, E, [], 3, 3, 0, 0, 0, BZ, 0, E, [BV], 0, 3, 0, 0, ["d", D(CP), "bY", H(FD), "ci", H(D5)], EM, 0, K, [], 0, 3, 0, 0, 0]);
    Cr([Bd, 0, E, [], 4, 3, 0, S, 0, Cn, 0, E, [], 3, 3, 0, 0, 0, BD, 0, BK, [Dh, Bl, Cn], 0, 3, 0, 0, ["d", D(C3), "bi", H(BO), "bl", H(Fg), "bQ", H(Fv), "o", D(DD), "bO", H(Dy), "cb", H(FR), "bI", D(DM)], Ey, 0, E, [], 4, 3, 0, 0, 0, N, 0, E, [Bl, Bt, BP], 0, 3, 0, Be, ["d", D(CM), "D", H(C1), "b$", H(Db), "bu", C8(Do), "bn", H(FV), "bm", D(E7), "bk", D(ET), "b6", M(Eg), "bd", H(EY), "b9", M(F2), "y", H(D3), "A", M(EB), "z", H(Ea), "f", D(Ez), "bb", H(F6)], BG, 0, E, [B8], 0, 3, 0, 0, ["d", D(C5), "U", H(Ev), "cg", H(FM)], Ds, 0, K, [], 0, 3, 0, 0, ["d", D(Ch)], E9, 0, E, [Bb], 1, 3, 0, 0, 0, Di, 0, E, [], 3, 3, 0, 0, 0, CY, 0, K, [], 0, 3, 0, 0, ["d",
        D(CA)], De, 0, E, [Di], 0, 0, 0, 0, ["w", H(Cp), "q", D(EZ), "r", D(Fo), "v", D(Dz)], C6, 0, E, [CW, Ci], 0, 3, 0, 0, ["n", D(DG), "l", D(D0)], CJ, 0, E, [], 3, 3, 0, 0, 0, CZ, 0, E, [CJ], 0, 3, 0, 0, ["d", D(Ck)]]);
    let Eu = Br(Cb), ED = Br(CQ);
    Eq(["<java_object>@", "img-", "images/", "0", "HI ", "   ", "ArrowDown", "Arrow", "Space", "Enter", "ArrowUp", "", "null", "/images/dino-run1.png", "/images/dino-run2.png", "/images/dino-dead.png", "/images/dino-jump.png", "/images/dino-duck1.png", "/images/dino-duck2.png", "/images/bird1.png", "/images/bird2.png", "/images/cactus1.png", "/images/cactus2.png", "/images/cactus3.png", "/images/big-cactus1.png", "/images/big-cactus2.png", "/images/big-cactus3.png", "/images/track.png", "/images/cloud.png", "/images/game-over.png", "/images/reset.png",
        "object", "function", "string", "number", "undefined"]);
    N.prototype.toString = function () { return Bn(this); };
    N.prototype.valueOf = N.prototype.toString; E.prototype.toString = function () { return Bn(CO(this)); };
    E.prototype.__teavm_class__ = function () { return FO(this); };
    let C = DA(FK);
    C.javaException = DI;
    let X = Symbol('jsoClass');
    (() => { let c; c = BH.prototype; c[X] = true; c.accept = c.cg; c = B2.prototype; c[X] = true; c.onTimer = c.ch; c = B1.prototype; c[X] = true; c.onTimer = c.ch; c = B0.prototype; c[X] = true; c.handleEvent = c.ci; c = BZ.prototype; c[X] = true; c.handleEvent = c.ci; c = BG.prototype; c[X] = true; c.accept = c.cg; })();
    main = C;
})();